export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT_SUCESSS = "LOGOUT_SUCESSS";

//Routing
export const ROUTES_CREATE = "ROUTES_CREATE";
export const ERROR_CREATING_ROUTE = "ERROR_CREATING_ROUTE";
export const ROUTES_LIST = "ROUTES_LIST";
export const ERROR_LIST_ROUTES = "ERROR_LIST_ROUTES";
export const GETTING_ROUTES_BY_ID = "GETTING_ROUTES_BY_ID";
export const ERROR_GETTING_ROUTES_BY_ID = "ERROR_GETTING_ROUTES_BY_ID";
export const ROUTES_DELETE = "ROUTES_DELETE";
export const ERROR_DELETE_ROUTES = "ERROR_DELETE_ROUTES";

//Stations
export const STATION_LIST = "STATION_LIST";
export const ERROR_STATION_LIST = "ERROR_STATION_LIST";
export const STATION_CREATE = "STATION_CREATE";
export const ERROR_STATION_CREATE = "ERROR_STATION_CREATE";
export const STATION_DELETE = "STATION_DELETE";
export const ERROR_DELETE_STATION = "ERROR_DELETE_STATION";

//Bus
export const BUS_LIST = "BUS_LIST";
export const ERROR_BUS_LIST = "ERROR_BUS_LIST";
export const BUS_CREATE = "BUS_CREATE";
export const ERROR_BUS_CREATE = "ERROR_BUS_CREATE";
export const BUS_DELETE = "BUS_DELETE";
export const ERROR_DELETE_BUS = "ERROR_DELETE_BUS";

//Drivers
export const DRIVER_LIST = "DRIVER_LIST";
export const ERROR_DRIVER_LIST = "ERROR_DRIVER_LIST";
export const DRIVER_CREATE = "DRIVER_CREATE";
export const ERROR_DRIVER_CREATE = "ERROR_DRIVER_CREATE";
export const DRIVER_DELETE = "DRIVER_DELETE";
export const ERROR_DELETE_DRIVER = "ERROR_DELETE_DRIVER";
